Parameters:
  VPCId:
    Description: Name of VPC Id from Output
    Type: String
  GatewayId:
    Description: Name of Gateway Id from Output
    Type: String

  DemoSubnetId:
    Description: Name of the Subnet Id to Output
    Type: String
  ImageId:
    Description: ami Image Id
    Type: String
  InstanceName:
    Description: Name of the instnce
    Type: String
  SecurityGroupName:
    Description: Name of the Security Group
    Type: String
  InstanceKeyName:
    Description: Name of the Security Group
    Type: String
  SecurityGroupEgressIP:
    Description: Egress IP range
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
    Default: 0.0.0.0/0
  SecurityGroupIngressIP:
    Description: Ingress IP range
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
    Default: 0.0.0.0/0

Resources:
  # EC2 instance
  ec2Instance:
    Type: AWS::EC2::Instance
    DependsOn: ["demoSG"]
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      KeyName: !Ref InstanceKeyName
      SecurityGroupIds: [!Ref demoSG]
      SubnetId: 
        Fn::ImportValue: !Ref DemoSubnetId
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
        - Key: "Project"
          Value: "atudevopsdemo"  
  
  demoSG:
    Type: AWS::EC2::SecurityGroup
    #DependsOn: demoVPC
    Properties:
      GroupDescription: Allow ssh to client host
      VpcId:
        Fn::ImportValue: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SecurityGroupEgressIP
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SecurityGroupIngressIP
      Tags:
       - Key: "Project"
         Value: atudevopsdemo1
       - Key: "Name"
         Value: !Ref SecurityGroupName