Resources:
  J:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      KeyName: demoKey1
      #SecurityGroupIds: ["demoSG1"]
      Tags:
        - Key: "Name"
          Value: "ec2au11"
        - Key: "Project"
          Value: "atudevopsdemo"  