Parameters:
  PublicSubnetId:
    Description: Name of Subnet Id variable from Output
    Type: String
  NATGatewayId:
    Description: Name of the NAT GatewayId to Output
    Type: String

Resources:
  # NAT Gateway meant for private subnet
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: 
        Fn::ImportValue: !Ref PublicSubnetId
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: !Ref NATGatewayId
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

# Exports
Outputs:
  demoNATGateway:
    Description: NAT Gateway Id
    Value: 
      Ref: NATGateway
    Export:
      Name: !Ref NATGatewayId