Parameters:
  VPCId:
    Description: Name of VPC Id from Output
    Type: String
  GatewayId:
    Description: Name of Gateway Id from Output
    Type: String

  demoSubnet1Id:
    Description: Name of the Subnet1 Id to Output
    Type: String
  demoSubnet2Id:
    Description: Name of the Subnet2 Id to Output
    Type: String

Resources:

  # Public Subnet
  demoSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: 'true'
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: !Ref demoSubnet1Id
  
  # Private Subnet      
  demoSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: 'false'
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: !Ref demoSubnet2Id

  # RouteTable for Subnet1
  demoRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue: !Ref VPCId
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: demoRouteTable1

  # Route for Subnet1
  demoRoute1:
    Type: AWS::EC2::Route
    #DependsOn: demoGatewayAttachment
    Properties:
      RouteTableId: !Ref demoRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: 
        Fn::ImportValue: !Ref GatewayId

  # Associate Subnet and Routtable
  demoSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref demoRouteTable1
      SubnetId: !Ref demoSubnet1


# Exports
Outputs:
  demoSubnet1:
    Description: Subnet 1 Id
    Value: 
      Ref: demoSubnet1
    Export:
      Name: !Ref demoSubnet1Id
  demoSubnet2:
    Description: Subnet 2 Id
    Value:
      Ref: demoSubnet2
    Export:
      Name: !Ref demoSubnet2Id