AWSTemplateFormatVersion: "2010-09-09"
Description: Create Subnet and Routetable
Parameters:
  VPCId:
    Description: Name of variable for VPC Id from Output
    Type: String
  GatewayId:
    Description: Name of variable for (NAT) Gateway Id from Output
    Type: String
  SubnetId:
    Description: Name of the variable for Subnet Id to Output
    Type: String
  RouteTableId:
    Description: Name of the variable for RouteTable Id to Output
    Type: String
  CidrBlock:
    Description: IP range for subnet
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  IsPublic:
    Description: Set whether the subnet is public; sets MapPublicIpOnLaunch = true
    Type: String
    Default: true
  SubnetDestinationCidrBlock:
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  AvailabilityZone:
    Description: Availability zone of subnet
    Type: String
    Default: "us-east-1a"
  HasNATGateway:
    Description: Whether we need (NAT) Gateway
    Type: String
    Default: false

Conditions:
  CreatePublicRoute: !Equals 
    - !Ref IsPublic
    - true
  
  # whether we need a route to NAT gateway
  CreateNATRoute: !Equals
    - !Ref HasNATGateway
    - true

Resources:

  # Subnet to hold an EC2 Instance or DBInstance
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      CidrBlock: !Ref CidrBlock
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: !Ref IsPublic
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: !Ref SubnetId

  # RouteTable for Subnet
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue: !Ref VPCId
      Tags:
       - Key: Project
         Value: atudevopsdemo1
       - Key: Name
         Value: !Ref RouteTableId

  # Associate Subnet and Routetable
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  # Route for Public Subnet
  GatewayRoute:
    Type: AWS::EC2::Route
    Condition: CreatePublicRoute
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: 
        Fn::ImportValue: !Ref GatewayId

  # Route for NAT Gateway
  NATGatewayRoute:
    Type: AWS::EC2::Route
    Condition: CreateNATRoute
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: 
        Fn::ImportValue: !Ref GatewayId

# Exports
Outputs:
  Subnet:
    Description: Subnet Id
    Value: 
      Ref: Subnet
    Export:
      Name: !Ref SubnetId

  RouteTable:
    Description: RouteTable Id
    Value: 
      Ref: RouteTable
    Export:
      Name: !Ref RouteTableId